[build]
target = "riscv32imafc-unknown-none-elf"

[target.riscv32imafc-unknown-none-elf]
# runner = 'riscv64-unknown-elf-gdb -x ../../openocd.gdb'
runner = [
    "probe-rs",
    "run",
    "--chip",
    "HPM6280",
    "--chip-description-path",
    "../../HPMicro.yaml",
    "--protocol",
    "jtag",
    "--log-format",
    "{t} {L} {fff}:{l} {s}",
]

rustflags = [
    # Zfh
    "-C",
    "target-feature=+d,+zfh",
    # Linker scripts:
    "-C",
    "link-arg=-Tmemory.x",
    "-C",
    "link-arg=-Tdevice.x", # __VECTORED_INTERRUPTS
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=-nmagic",

    # "--emit", "obj",
    # "--emit", "asm",
]

[unstable]
build-std = ["core"]

[env]
DEFMT_LOG = "info"
