[build]
target = "riscv32imafc-unknown-none-elf"

[target.riscv32imafc-unknown-none-elf]
# runner = 'riscv64-unknown-elf-gdb -x ../../openocd.gdb'
runner = [
    "probe-rs",
    "run",
    "--chip",
    "HPM5361",
    "--chip-description-path",
    "../../HPMicro.yaml",
    "--protocol",
    "jtag",
    "--log-format",
    "{t} {L} {fff}:{l} {s}",
]

rustflags = [
    # Target features:
    # The default for imacf is is "+m,+a,+c,+f"
    "-C",
    "target-feature=+zba,+zbb,+zbc,+zbs,+d",
    # Linker scripts:
    "-C",
    "link-arg=-Tmemory.x",
    "-C",
    "link-arg=-Tdevice.x", # __VECTORED_INTERRUPTS, peripheral interrupt names
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=-nmagic",

    # "--emit", "obj",
    # "--emit", "asm",
]

[unstable]
build-std = ["core"]

[env]
DEFMT_LOG = "trace"
