use crate::pac;

// We need to export this in the hal for the drivers to use

crate::peripherals! {
    GPIO0 <= GPIO0,
    // Fast GPIO controller
    FGPIO0 <= FGPIO,
    // Power domain GPIO controller
    PGPIO <= PGPIO,

    UART0 <= UART0,
    UART1 <= UART1,
    UART2 <= UART2,
    UART3 <= UART3,
    UART4 <= UART4,
    UART5 <= UART5,
    UART6 <= UART6,
    UART7 <= UART7,

    I2C0 <= I2C0,
    I2C1 <= I2C1,
    I2C2 <= I2C2,
    I2C3 <= I2C3,

    SPI0 <= SPI0,
    SPI1 <= SPI1,
    SPI2 <= SPI2,
    SPI3 <= SPI3,

    CAN0 <= MCAN0,
    CAN1 <= MCAN1,
    CAN2 <= MCAN2,
    CAN3 <= MCAN3,

    ADC0 <= ADC0,
    ADC1 <= ADC1,

    DAC0 <= DAC0,
    DAC1 <= DAC1,

    PA00 <= virtual,
    PA01 <= virtual,
    PA02 <= virtual,
    PA03 <= virtual,
    PA04 <= virtual,
    PA05 <= virtual,
    PA06 <= virtual,
    PA07 <= virtual,
    PA08 <= virtual,
    PA09 <= virtual,
    PA10 <= virtual,
    PA11 <= virtual,
    PA12 <= virtual,
    PA13 <= virtual,
    PA14 <= virtual,
    PA15 <= virtual,
    PA16 <= virtual,
    PA17 <= virtual,
    PA18 <= virtual,
    PA19 <= virtual,
    PA20 <= virtual,
    PA21 <= virtual,
    PA22 <= virtual,
    PA23 <= virtual,
    PA24 <= virtual,
    PA25 <= virtual,
    PA26 <= virtual,
    PA27 <= virtual,
    PA28 <= virtual,
    PA29 <= virtual,
    PA30 <= virtual,
    PA31 <= virtual,
    PB00 <= virtual,
    PB01 <= virtual,
    PB02 <= virtual,
    PB03 <= virtual,
    PB04 <= virtual,
    PB05 <= virtual,
    PB06 <= virtual,
    PB07 <= virtual,
    PB08 <= virtual,
    PB09 <= virtual,
    PB10 <= virtual,
    PB11 <= virtual,
    PB12 <= virtual,
    PB13 <= virtual,
    PB14 <= virtual,
    PB15 <= virtual,
    PX00 <= virtual,
    PX01 <= virtual,
    PX02 <= virtual,
    PX03 <= virtual,
    PX04 <= virtual,
    PX05 <= virtual,
    PX06 <= virtual,
    PX07 <= virtual,
    PY00 <= virtual,
    PY01 <= virtual,
    PY02 <= virtual,
    PY03 <= virtual,
    PY04 <= virtual,
    PY05 <= virtual,
    PY06 <= virtual,
    PY07 <= virtual,
}
