name: CI build

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - hpm5300evk
          - hpm6200evk
          - hpm6300evk
          - hpm6750evkmini
          - hpm6e00evk
    name: Build ${{ matrix.board }}
    steps:
      - uses: actions/checkout@v3
      - name: Use nightly Rust
        run: |
          rustup default nightly
          rustup component add rust-src
          rustup target add riscv32imafc-unknown-none-elf
      - name: Build
        run: cargo build --release
        working-directory: examples/${{ matrix.board }}
